### ISSUE TITLE
NULL results now and then

### ISSUE THREAD

**Issue by cvermehren** [Leszek-Sieminski/pagespeedParseR#9]
Hello Leszek,

Thanks for this very useful package!

I am testing it out and it works great for most URLs that I use. However, sometime I experience that the API returns NULL. I suppose this is some instability in the pageSpeed API, but I just wondered if you have had the same experience or any suggestions as to how to work around it?

Thanks
Christian

**Comment by Leszek-Sieminski** [comment]
Hi Christian!
Thanks for your kind words.
You've created this issue twice, so I will close this one and reply to you in the other one.
